version: '3.8'

services:
  postgres_order:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADV/ERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  order:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_order:5432/orderdb
      - REDIS_URL=redis://redis:6379
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - postgres_order
      - redis
      - kafka
      - mongo

  order_celery_worker:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: celery -A src.infrastructure.outbox.celery_worker.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_order:5432/orderdb
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - order
      - redis
      - kafka
      - mongo

  order_projection_worker:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: python src/infrastructure/projection/worker.py
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - order
      - redis
      - mongo