version: '3.8'

services:
  postgres_order:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"

  postgres_basket:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basketdb
    ports:
      - "5434:5432"

  postgres_product:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5435:5432"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # --- ORDER SERVICE ---
  order:
    build:
      context: ./Order
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_order:5432/orderdb
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - postgres_order
      - redis
      - kafka
      - mongo

  order_celery_worker:
    build:
      context: ./Order
      dockerfile: Dockerfile
    command: celery -A src.infrastructure.outbox.celery_worker.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_order:5432/orderdb
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - order
      - redis
      - kafka
      - mongo

  order_projection_worker:
    build:
      context: ./Order
      dockerfile: Dockerfile
    command: python src/infrastructure/projection/worker.py
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - order
      - redis
      - mongo

  # --- BASKET SERVICE ---
  basket:
    build:
      context: ./Basket
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_basket:5432/basketdb
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - postgres_basket
      - redis
      - kafka
      - mongo

  basket_celery_worker:
    build:
      context: ./Basket
      dockerfile: Dockerfile
    command: celery -A src.infrastructure.outbox.celery_worker.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_basket:5432/basketdb
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - basket
      - redis
      - kafka
      - mongo

  basket_projection_worker:
    build:
      context: ./Basket
      dockerfile: Dockerfile
    command: python src/infrastructure/projection/worker.py
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - basket
      - redis
      - mongo

  # --- PRODUCT SERVICE ---
  product:
    build:
      context: ./Product
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8002 --reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_product:5432/productdb
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - postgres_product
      - redis
      - kafka
      - mongo

  product_celery_worker:
    build:
      context: ./Product
      dockerfile: Dockerfile
    command: celery -A src.infrastructure.outbox.celery_worker.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_product:5432/productdb
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BOOTSTRAP=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - product
      - redis
      - kafka
      - mongo

  product_projection_worker:
    build:
      context: ./Product
      dockerfile: Dockerfile
    command: python src/infrastructure/projection/worker.py
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - product
      - redis
      - mongo