services:
  basket:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: basket_service
    ports:
      - "5001:8000"
    depends_on:
      - redis
      - kafka
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MESSAGE_BUS_BACKEND: kafka
      KAFKA_BOOTSTRAP: kafka:9092
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper_order:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper_order
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_order:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
